2021-04-18T14:31:24: PM2 log: ===============================================================================
2021-04-18T14:31:24: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
2021-04-18T14:31:24: PM2 log: Time                 : Sun Apr 18 2021 14:31:24 GMT-0300 (Brasilia Standard Time)
2021-04-18T14:31:24: PM2 log: PM2 version          : 4.5.6
2021-04-18T14:31:24: PM2 log: Node.js version      : 14.15.4
2021-04-18T14:31:24: PM2 log: Current arch         : arm64
2021-04-18T14:31:24: PM2 log: PM2 home             : /data/data/com.termux/files/home/.pm2
2021-04-18T14:31:24: PM2 log: PM2 PID file         : /data/data/com.termux/files/home/.pm2/pm2.pid
2021-04-18T14:31:24: PM2 log: RPC socket file      : /data/data/com.termux/files/home/.pm2/rpc.sock
2021-04-18T14:31:24: PM2 log: BUS socket file      : /data/data/com.termux/files/home/.pm2/pub.sock
2021-04-18T14:31:24: PM2 log: Application log path : /data/data/com.termux/files/home/.pm2/logs
2021-04-18T14:31:24: PM2 log: Worker Interval      : 30000
2021-04-18T14:31:24: PM2 log: Process dump file    : /data/data/com.termux/files/home/.pm2/dump.pm2
2021-04-18T14:31:24: PM2 log: Concurrent actions   : 2
2021-04-18T14:31:24: PM2 log: SIGTERM timeout      : 1600
2021-04-18T14:31:24: PM2 log: ===============================================================================
2021-04-18T14:31:24: PM2 log: App [index:0] starting in -fork mode-
2021-04-18T14:31:24: PM2 log: App [index:0] online
2021-04-18T14:31:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:31:25: PM2 error: Error while getting CLK_TCK Error: Command failed: getconf CLK_TCK
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'getconf CLK_TCK'
}
2021-04-18T14:31:25: PM2 error: Error while getting PAGESIZE Error: Command failed: getconf PAGESIZE
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'getconf PAGESIZE'
}
2021-04-18T14:31:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:32:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:31: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:32: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:33: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:34: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:36: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:37: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:38: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:39: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:40: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:41: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:44: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:45: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:46: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:47: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:48: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:49: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:50: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:51: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:52: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:33:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:11: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:12: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:13: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:14: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:16: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:17: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:18: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:19: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:20: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:21: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:22: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:23: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:24: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:26: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:27: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:28: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:30: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:34:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:35:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:35:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:36:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:36:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:37:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:37:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:38:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:38:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:39:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:39:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:40:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:40:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:41:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:41:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:42:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:42:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:43:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:43:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:44:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:44:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:45:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:45:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:46:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:46:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:47:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:47:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:48:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:48:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:49:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:49:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:50:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:50:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:51:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:51:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:52:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:52:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:53:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:53:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:54:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:54:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:55:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:55:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:56:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:56:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:57:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:57:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:58:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:58:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:59:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T14:59:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:00:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:00:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:01:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:01:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:02:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:02:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:03:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:03:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:04:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:04:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:05:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:05:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:06:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:06:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:07:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:07:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:08:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:08:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:09:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:09:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:10:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:10:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:11:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:11:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:12:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:12:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:13:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:13:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:14:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:14:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:15:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:15:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:16:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:16:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:17:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:17:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:18:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:18:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:19:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:19:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:20:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:20:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:21:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:21:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:22:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:22:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:23:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:23:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:24:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:24:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:25:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:25:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:26:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:26:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:27:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:27:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:28:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:28:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:29:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:29:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:30:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:30:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:31:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:31:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:32:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:32:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:33:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:33:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:34:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:34:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:35:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:35:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:36:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:36:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:37:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:37:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:38:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:38:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:39:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:39:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:40:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:40:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:41:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:41:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:42:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:42:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:43:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:43:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:44:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:44:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:45:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:45:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:46:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:46:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:47:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:47:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:48:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:48:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:49:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:49:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:50:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:50:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:51:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:51:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:52:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:52:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-04-18T15:53:25: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
